# Generated by Django 2.2.24 on 2021-10-06 21:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=512, null=True, unique=True)),
                ('level', models.IntegerField(help_text='The lower this value, the higher this type is in the organization.', unique=True)),
                ('parent', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.OrganizationLevel')),
            ],
            options={
                'ordering': ['-level'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(max_length=512, null=True, unique=True)),
                ('shortname', models.CharField(max_length=1024, null=True, unique=True)),
                ('longname', models.CharField(max_length=2048, null=True, unique=True)),
                ('organization_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.OrganizationLevel')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
            ],
            options={
                'ordering': ['shortname'],
            },
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('code', 'parent'), name='organization_code_parent_unique'),
        ),
    ]
